spring:
  cloud:
    gateway:
      routes:

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-User-Header, UserValue

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
            - Method=POST
          filters:
            - RewritePath=/order/(.*), /api/orders/$1
            - AddResponseHeader=X-Order-Header, OrderValue

        - id: random-strategy-route
          uri: lb://your-service-name  # 指定服务名称
          predicates:
            - Path=/your-url/**        # 指定匹配的 URL 路径
          filters:
            - name: LoadBalancerClient
              args:
                loadBalancerClientFilter:
                  # 指定随机负载均衡策略
                  loadBalancer: org.springframework.cloud.loadbalancer.core.RandomLoadBalancer
